#!/usr/bin/env python3
"""根据 Q1 公司对关系 CSV + 公司月度计数 JSON，生成弦图时间序列数据。

月度权重（无向）：对在 CSV 中出现的公司对 (a,b)，取当月 min(count_a, count_b)×confidence，
反映「双方在当月均有贸易且关系置信度高」时的连带强度。节点集：关系中出现频次最高的前 N 家公司。

输出：
  visualization/q1/data/q1_relationship_chord_data.js  — 供 HTML 直接引用（避免 file:// 下 fetch 失败）
  visualization/q1/data/q1_relationship_chord.json      — 同源 JSON 备份
"""

from __future__ import annotations

import json
import math
import sys
from collections import Counter
from pathlib import Path

import numpy as np
import pandas as pd

_vis_root = Path(__file__).resolve().parents[1]
if str(_vis_root) not in sys.path:
    sys.path.insert(0, str(_vis_root))

from figures2d_common import OUTPUTS_DIR_Q1, ensure_dirs, load_q1_patterns

_OUT_DIR = Path(__file__).resolve().parent / "data"

MAX_NODES = 30
MIN_CONFIDENCE = 0.6


def _month_range_inclusive(start_ym: str, end_ym: str) -> list[str]:
    if not start_ym or not end_ym or len(start_ym) < 7 or len(end_ym) < 7:
        return []
    dr = pd.period_range(start=start_ym[:7], end=end_ym[:7], freq="M")
    return [str(p) for p in dr]


def _temporal_monthly_map(patterns: list[dict]) -> dict[str, dict[str, int]]:
    out: dict[str, dict[str, int]] = {}
    for row in patterns:
        c = row.get("company")
        if not c:
            continue
        mc = row.get("monthly_counts") or {}
        out[str(c)] = {str(k): int(v) for k, v in mc.items()}
    return out


def main() -> None:
    ensure_dirs()
    _OUT_DIR.mkdir(parents=True, exist_ok=True)

    csv_path = OUTPUTS_DIR_Q1 / "q1_relationship_patterns.csv"
    if not csv_path.is_file():
        print(f"Missing {csv_path}", file=sys.stderr)
        sys.exit(1)

    df = pd.read_csv(csv_path, encoding="utf-8-sig")
    df = df[df["confidence"].astype(float) >= MIN_CONFIDENCE].copy()

    cnt: Counter[str] = Counter()
    for _, r in df.iterrows():
        cnt[str(r["company_a"])] += 1
        cnt[str(r["company_b"])] += 1

    top_nodes = [n for n, _ in cnt.most_common(MAX_NODES)]
    nodes_set = set(top_nodes)
    df_sub = df[
        df["company_a"].astype(str).isin(nodes_set) & df["company_b"].astype(str).isin(nodes_set)
    ].copy()

    nodes = sorted(nodes_set, key=lambda x: (-cnt[x], x))
    idx = {name: i for i, name in enumerate(nodes)}
    n = len(nodes)

    pair_pattern: dict[str, str] = {}
    pair_confidence: dict[str, float] = {}
    for _, r in df_sub.iterrows():
        a, b = str(r["company_a"]), str(r["company_b"])
        if a not in idx or b not in idx:
            continue
        lo, hi = (a, b) if a <= b else (b, a)
        key = f"{lo}|||{hi}"
        conf = float(r["confidence"])
        if key not in pair_confidence or conf > pair_confidence[key]:
            pair_confidence[key] = conf
            pair_pattern[key] = str(r["relationship_pattern"])

    temporal = _temporal_monthly_map(load_q1_patterns())

    month_keys: set[str] = set()
    for name in nodes:
        month_keys.update(temporal.get(name, {}).keys())

    if not month_keys:
        print("No monthly_counts for selected nodes.", file=sys.stderr)
        sys.exit(1)

    months_sorted = sorted(month_keys)
    months_full = _month_range_inclusive(months_sorted[0], months_sorted[-1])

    matrices: list[list[list[float]]] = []
    for month in months_full:
        mat = np.zeros((n, n), dtype=np.float64)
        for _, r in df_sub.iterrows():
            a, b = str(r["company_a"]), str(r["company_b"])
            if a not in idx or b not in idx:
                continue
            i, j = idx[a], idx[b]
            ca = float(temporal.get(a, {}).get(month, 0))
            cb = float(temporal.get(b, {}).get(month, 0))
            if ca <= 0 or cb <= 0:
                continue
            w = math.sqrt(ca * cb) * float(r["confidence"])
            mat[i, j] += w
            mat[j, i] = mat[i, j]
        matrices.append(mat.tolist())

    payload = {
        "description": "Chord weights = sqrt(monthly_counts[a]*monthly_counts[b])*confidence for CSV pairs; nodes top by pair frequency.",
        "max_nodes": MAX_NODES,
        "min_confidence": MIN_CONFIDENCE,
        "nodes": nodes,
        "node_labels": [str(nm)[:26] + ("…" if len(str(nm)) > 26 else "") for nm in nodes],
        "months": months_full,
        "matrices": matrices,
        "pair_pattern": pair_pattern,
        "pair_confidence": {k: round(v, 4) for k, v in pair_confidence.items()},
    }

    json_path = _OUT_DIR / "q1_relationship_chord.json"
    json_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")

    js_path = _OUT_DIR / "q1_relationship_chord_data.js"
    js_body = (
        "// Auto-generated by visualization/q1/build_q1_relationship_chord_data.py\n"
        "window.Q1_RELATIONSHIP_CHORD = "
        + json.dumps(payload, ensure_ascii=False)
        + ";\n"
    )
    js_path.write_text(js_body, encoding="utf-8")

    print(f"Nodes={n}, months={len(months_full)}, pairs_used={len(df_sub)}")
    print(f"Wrote {json_path}")
    print(f"Wrote {js_path}")


if __name__ == "__main__":
    main()
